services:
  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379

  api:
    build: .
    env_file:
      - .env
    ports:
      - ${API_PORT}:8000
    depends_on:
      - redis
    environment:
      PYTHONPATH: /app/src
    volumes:
      - ./downloads:/app/downloads

  worker:
    build: .
    env_file:
      - .env
    command: uv run rq worker
    depends_on:
      - redis
    environment:
      PYTHONPATH: /app/src
    volumes:
      - ./downloads:/app/downloads